"""Response hardening headers (Phase 7).

Headers are only worth adding if they are actually emitted on every response,
including the ones the framework generates on its own, so these tests check error
responses and probe responses too - not just a happy-path 200.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from app.core.config import Settings
from app.main import app, create_app
from app.middleware.security_headers import API_CSP, DOCS_CSP

GOOD_SECRET = "a-sufficiently-long-test-secret-key-1234"


def settings_for(**overrides: object) -> Settings:
    base: dict[str, object] = {"environment": "local", "jwt_secret_key": GOOD_SECRET}
    return Settings(_env_file=None, **{**base, **overrides})  # type: ignore[arg-type]


@pytest.fixture
def app_client() -> TestClient:
    """The real application, so these tests describe what is actually shipped."""
    return TestClient(app)


# ---------------------------------------------------------------------------
# The headers themselves
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("header", "value"),
    [
        # A JSON body containing attacker-influenced text must never be sniffed as
        # HTML and executed.
        ("X-Content-Type-Options", "nosniff"),
        # Karya's URLs contain user and tenant UUIDs; a Referer header would leak
        # them to whatever site the browser navigates to next.
        ("Referrer-Policy", "no-referrer"),
        ("X-Frame-Options", "DENY"),
        # Every response here is authenticated data or an error. Neither belongs in
        # a shared cache or on a laptop's disk.
        ("Cache-Control", "no-store"),
    ],
)
def test_security_headers_are_present(
    app_client: TestClient, header: str, value: str
) -> None:
    assert app_client.get("/health").headers[header] == value


def test_api_responses_get_the_strict_csp(app_client: TestClient) -> None:
    """An API response may load nothing, execute nothing and be framed by nothing."""
    policy = app_client.get("/health").headers["Content-Security-Policy"]

    assert policy == API_CSP
    assert "default-src 'none'" in policy
    assert "frame-ancestors 'none'" in policy


@pytest.mark.parametrize(
    "path",
    ["/health", "/ready", "/api/v1/auth/me", "/api/v1/users", "/nonexistent"],
)
def test_headers_are_present_on_error_responses_too(
    app_client: TestClient, path: str
) -> None:
    """Including 401s and 404s that the framework generates without a handler.

    This is the case a middleware placed in the wrong position gets wrong, so it is
    checked explicitly rather than assumed from the 200 above.
    """
    response = app_client.get(path)

    assert response.headers["X-Content-Type-Options"] == "nosniff"
    assert response.headers["Content-Security-Policy"] == API_CSP


def test_headers_are_present_on_a_413(app_client: TestClient) -> None:
    """A response generated by an inner middleware still passes through."""
    response = app_client.post(
        "/api/v1/auth/login",
        content=b"x" * 100_000,
        headers={"Content-Type": "application/json"},
    )

    assert response.status_code == 413
    assert response.headers["X-Content-Type-Options"] == "nosniff"
    assert response.headers["Cache-Control"] == "no-store"


# ---------------------------------------------------------------------------
# The documentation pages are a genuine exception
# ---------------------------------------------------------------------------


def test_docs_get_a_relaxed_csp_and_still_render(app_client: TestClient) -> None:
    """Swagger UI is a real HTML document that loads a script from a CDN and
    mounts itself via a second, inline script FastAPI embeds directly.

    The strict API policy would render a blank page - not just from the missing
    CDN allowance, but because a browser silently blocks that inline mounting
    script without `'unsafe-inline'` on `script-src` too. Both relaxations are
    scoped to exactly the documentation paths, so they cost nothing on any route
    that carries data (see the `DOCS_CSP` docstring for why this is safe there).
    """
    response = app_client.get("/docs")

    assert response.status_code == 200
    assert response.headers["Content-Security-Policy"] == DOCS_CSP
    assert "cdn.jsdelivr.net" in response.headers["Content-Security-Policy"]
    assert "'unsafe-inline'" in DOCS_CSP.split("script-src")[1].split(";")[0]
    # The page really is the Swagger UI, not an empty shell.
    assert "swagger-ui" in response.text


def test_the_relaxed_policy_is_confined_to_the_docs(app_client: TestClient) -> None:
    assert app_client.get("/openapi.json").headers["Content-Security-Policy"] == API_CSP


# ---------------------------------------------------------------------------
# HSTS is conditional, and that condition matters
# ---------------------------------------------------------------------------


def test_hsts_is_absent_locally(app_client: TestClient) -> None:
    assert "Strict-Transport-Security" not in app_client.get("/health").headers


def test_hsts_is_sent_when_enabled() -> None:
    configured = create_app(settings_for(hsts_enabled=True))

    with TestClient(configured) as configured_client:
        header = configured_client.get("/health").headers["Strict-Transport-Security"]

    assert "max-age=31536000" in header
    assert "includeSubDomains" in header


def test_hsts_max_age_is_configurable() -> None:
    configured = create_app(
        settings_for(hsts_enabled=True, hsts_max_age_seconds=600)
    )

    with TestClient(configured) as configured_client:
        header = configured_client.get("/health").headers["Strict-Transport-Security"]

    assert "max-age=600" in header


# ---------------------------------------------------------------------------
# Nothing about the server is advertised
# ---------------------------------------------------------------------------


def test_no_response_advertises_the_stack(app_client: TestClient) -> None:
    """Version banners tell an attacker which CVEs to try first.

    Uvicorn sets ``server: uvicorn``, which is generic enough to be harmless, but
    nothing may carry a version or a framework name.
    """
    headers = app_client.get("/health").headers

    assert "X-Powered-By" not in headers
    for name, value in headers.items():
        assert "fastapi" not in value.lower(), name
        assert "starlette" not in value.lower(), name
        assert "python" not in value.lower(), name


def test_docs_can_be_switched_off_entirely() -> None:
    """A deployment that would rather not publish its schema can turn it off.

    Both the UI and the schema go together - they are one decision.
    """
    hidden = create_app(settings_for(docs_enabled=False))

    with TestClient(hidden) as hidden_client:
        assert hidden_client.get("/docs").status_code == 404
        assert hidden_client.get("/openapi.json").status_code == 404
        assert hidden_client.get("/redoc").status_code == 404
        # The API itself is unaffected.
        assert hidden_client.get("/health").status_code == 200
        assert hidden_client.get("/api/v1/auth/me").status_code == 401
