/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is running. Never touches the database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether a trivial query against PostgreSQL succeeds.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate within a tenant and obtain tokens
         * @description Exchange tenant slug + email + password for an access/refresh pair.
         *
         *     Returns the same 401 whether the tenant is unknown, the user is unknown, the
         *     password is wrong, or the account is inactive.
         *
         *     Failed attempts are counted per (tenant, email) and the counter is cleared on
         *     success, so repeated guessing against one account is throttled while a person
         *     who mistypes once and then succeeds is not. The 429 that throttling produces is
         *     identical for an account that exists and one that does not - the
         *     anti-enumeration property has to hold for every status code, not only 401.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a new token pair
         * @description Rotate the supplied refresh token.
         *
         *     The presented token is revoked as part of a successful rotation, so
         *     presenting it a second time fails. Rejection is never downgraded to
         *     "issue a new token anyway".
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Revoke the supplied refresh token.
         *
         *     Idempotent, and returns 204 even for an unknown or already-revoked token so
         *     the endpoint cannot be used to probe which tokens exist. Access tokens are
         *     short-lived and are not blacklisted in this phase.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated user
         * @description Return the caller's own profile.
         *
         *     Identity comes exclusively from the validated bearer token; any ``user_id``,
         *     ``tenant_id`` or ``role`` supplied as a query parameter, header or body is
         *     ignored. The response never includes ``password_hash``.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/qr/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived QR challenge for the office display
         * @description Mint a new dynamic QR challenge for the caller's own tenant.
         *
         *     The tenant and its attendance location are resolved from the authenticated
         *     user, so a caller cannot issue a challenge for anyone else's site. The
         *     challenge is single-use and expires after the configured TTL; the display is
         *     expected to re-request one shortly before it lapses.
         */
        post: operations["create_qr_challenge_api_v1_presence_qr_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify physical presence from GPS and QR evidence
         * @description Evaluate GPS + QR evidence for the authenticated user.
         *
         *     Open to any authenticated, active user of the tenant - STAFF included, since
         *     proving one's own presence is the normal staff action.
         *
         *     A rejection is returned as **200 with ``verified: false``**, not a 4xx: the
         *     request was well-formed and processed, and the body carries a structured
         *     verdict per signal. HTTP error codes are reserved for requests that could
         *     not be processed at all (401 unauthenticated, 422 malformed evidence).
         *
         *     The commit persists the audit row and, on success, the QR consumption.
         */
        post: operations["verify_presence_api_v1_presence_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check in, after verifying presence
         * @description Record a CHECK_IN for the authenticated user.
         *
         *     Presence is verified here as part of the action - a prior call to
         *     ``/presence/verify`` neither helps nor is trusted. The user must currently
         *     be ``NOT_CHECKED_IN``; a duplicate attempt is refused with
         *     ``ALREADY_CHECKED_IN`` and, deliberately, without consuming the QR
         *     challenge.
         */
        post: operations["check_in_api_v1_attendance_check_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out, after verifying presence
         * @description Record a CHECK_OUT for the authenticated user.
         *
         *     Requires a preceding CHECK_IN: without one the attempt is refused with
         *     ``NOT_CHECKED_IN``. Needs its own fresh QR challenge, since the one that
         *     authorised the check-in was consumed by it.
         */
        post: operations["check_out_api_v1_attendance_check_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own attendance for a day
         * @description Return the authenticated user's attendance, defaulting to today (UTC).
         *
         *     Identity comes from the bearer token; a ``user_id`` in the query string, a
         *     header or a body is ignored entirely. There is no way to ask this endpoint
         *     about anybody else.
         */
        get: operations["read_my_attendance_api_v1_attendance_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/me/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own attendance history
         * @description Paginated daily history for the authenticated user, newest day first.
         */
        get: operations["read_my_history_api_v1_attendance_me_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/team/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's attendance across the caller's tenant
         * @description Every active user in the caller's own tenant, with today's attendance.
         *
         *     The tenant comes from the authenticated user, so there is no parameter that
         *     could widen the query to another tenant. Users with no events still appear,
         *     as ``NO_RECORD`` - they are precisely who a manager is looking for.
         */
        get: operations["read_team_attendance_api_v1_attendance_team_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One tenant user's attendance for a day
         * @description Attendance for one user in the caller's own tenant.
         *
         *     A user id belonging to a different tenant returns **404**, identical to an id
         *     that does not exist anywhere. Distinguishing the two would confirm the id is
         *     real and turn this into a cross-tenant enumeration oracle.
         */
        get: operations["read_user_attendance_api_v1_attendance_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/users/{user_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One tenant user's attendance history
         * @description Paginated daily history for one user in the caller's own tenant.
         *
         *     Remains available for **inactive** users: they are excluded from the live
         *     dashboard, but their recorded history is an audit record and is never hidden
         *     or deleted.
         */
        get: operations["read_user_history_api_v1_attendance_users__user_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own profile
         * @description Return the authenticated user's profile.
         *
         *     Identity comes from the bearer token; no id is accepted. Never includes
         *     ``password_hash`` or any token.
         */
        get: operations["read_own_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the caller's own profile
         * @description Update the caller's own safe profile fields.
         *
         *     Only ``name`` is writable here. Role, status, tenant and email are not - they
         *     are administrative or identity concerns, and a schema that never declares them
         *     rejects an attempt to send one with a 422.
         */
        patch: operations["update_own_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the caller's own password
         * @description Change the authenticated user's password.
         *
         *     The current password is verified before anything about the new one is
         *     considered, so the endpoint answers no questions for a caller who has not
         *     proven they own the account. A wrong current password returns 401 with a
         *     generic message - never a hint about the new password's acceptability.
         *
         *     Every refresh session is revoked on success: a password change usually means
         *     the old one is suspect, and a 30-day refresh token would otherwise keep
         *     whoever knew it signed in.
         */
        post: operations["change_own_password_api_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users in the caller's tenant
         * @description One page of the caller's own tenant's users.
         *
         *     Filtering and search happen in SQL - the tenant is never loaded into memory to
         *     be sifted - and the search term is a bound parameter, so wildcards and quotes
         *     are matched literally rather than altering the query. Page size is capped.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * Create a user in the caller's tenant
         * @description Create a user inside the administrator's own tenant.
         *
         *     The tenant is taken from the authenticated administrator - there is no
         *     ``tenant_id`` field, so a user cannot be created anywhere else. The password is
         *     hashed with Argon2id and never echoed back.
         *
         *     A duplicate email or employee code surfaces as a clean 409; the underlying
         *     constraint violation never reaches the client.
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one user in the caller's tenant
         * @description Read one user from the caller's own tenant.
         *
         *     An id belonging to another tenant returns 404, identical to an id that exists
         *     nowhere - distinguishing them would confirm the id is real and allow
         *     cross-tenant enumeration.
         */
        get: operations["read_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update one user's profile
         * @description Update a user's profile fields.
         *
         *     Writable: ``email``, ``name``, ``employee_code``. Not writable here: ``role``
         *     and ``status``, which have dedicated endpoints so a privilege change is never
         *     indistinguishable from a typo correction in the audit trail.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change one user's role
         * @description Change a user's role within the caller's tenant.
         *
         *     Refused if the target is the caller: nobody edits their own role, which closes
         *     the most direct escalation path. Also refused if it would demote the tenant's
         *     last active administrator. ``SUPER_ADMIN`` is not an assignable role.
         */
        patch: operations["change_user_role_api_v1_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate a user
         * @description Deactivate a user - a lifecycle change, never a delete.
         *
         *     The account can no longer log in, refresh, check in or check out, and its
         *     refresh sessions are revoked immediately. Attendance events and audit rows are
         *     untouched, so history stays complete and still resolves to a real identity.
         */
        post: operations["deactivate_user_api_v1_users__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivate a user
         * @description Reactivate a user, restoring their ability to authenticate.
         *
         *     Their password is left alone - reactivation is not a credential reset, and
         *     silently clearing one would lock the person out instead.
         */
        post: operations["activate_user_api_v1_users__user_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One user's lifecycle audit history
         * @description Lifecycle audit rows for one user, newest first.
         *
         *     Scoped to the tenant, to ``target_type='User'`` and to this user, so it is not
         *     a window onto the tenant's whole audit log - attendance and QR rows are not
         *     reachable here. The metadata contains only identifiers and before/after values.
         */
        get: operations["read_user_audit_api_v1_users__user_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own tenant
         * @description Return the tenant the authenticated user belongs to.
         *
         *     Open to any active user: knowing which organisation you work for is not
         *     privileged. The response carries no user counts, credentials or configuration.
         */
        get: operations["read_own_tenant_api_v1_tenant_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the caller's own tenant
         * @description Update the tenant's display name.
         *
         *     Only ``name``. ``slug`` is excluded despite looking like ordinary metadata: it
         *     is the identifier every employee types at login, so renaming it would lock out
         *     the whole company at once.
         */
        patch: operations["update_own_tenant_api_v1_tenant_me_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttendanceActionRequest
         * @description Evidence for a check-in or check-out.
         *
         *     Identical to the presence contract: coordinates, accuracy, challenge id and
         *     nonce. Note what is *absent* - no user, no tenant, no timestamp, no event
         *     type and no verdict. Those are all determined by the server, and inherited
         *     ``extra="forbid"`` turns an attempt to supply one into a 422 rather than a
         *     silently ignored field.
         */
        AttendanceActionRequest: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accuracy Meters */
            accuracy_meters: number;
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Nonce */
            nonce: string;
        };
        /**
         * AttendanceActionResponse
         * @description The outcome of a check-in or check-out attempt.
         *
         *     A refusal is reported as ``success: false`` with HTTP 200, matching
         *     ``/presence/verify``. The request was well-formed and fully processed; the
         *     answer is "no, and here is exactly why". Returning the presence breakdown
         *     alongside the reason is what lets a client tell the user *"you are 350 m
         *     away"* rather than just *"failed"*. HTTP error codes stay reserved for
         *     requests that could not be processed at all - 401 unauthenticated, 422
         *     malformed or smuggled fields.
         */
        AttendanceActionResponse: {
            /** Success */
            success: boolean;
            event_type: components["schemas"]["AttendanceEventType"];
            status: components["schemas"]["AttendanceState"];
            /** Attendance Event Id */
            attendance_event_id?: string | null;
            /** Event Timestamp */
            event_timestamp?: string | null;
            presence?: components["schemas"]["PresenceSummary"] | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * AttendanceDayResponse
         * @description One user's attendance for one UTC calendar day.
         *
         *     ``NO_RECORD`` means no attendance event was recorded - **not** that the
         *     person was absent from work. Karya cannot distinguish leave, travel, or a
         *     failure to reach the QR display.
         */
        AttendanceDayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["DayStatus"];
            /** Sessions */
            sessions?: components["schemas"]["AttendanceSessionResponse"][];
            /** First Check In */
            first_check_in?: string | null;
            /** Last Check Out */
            last_check_out?: string | null;
        };
        /**
         * AttendanceEventType
         * @description Kind of attendance event.
         * @enum {string}
         */
        AttendanceEventType: "CHECK_IN" | "CHECK_OUT";
        /**
         * AttendanceHistoryResponse
         * @description A page of daily attendance, newest day first.
         *
         *     Every date in the requested range appears, including days with no events, so
         *     a calendar can distinguish "nothing recorded" from "outside the range".
         */
        AttendanceHistoryResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Items */
            items: components["schemas"]["AttendanceDayResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        /**
         * AttendanceSessionResponse
         * @description One check-in/check-out pair.
         *
         *     Either side may be ``null``: an open session has no ``check_out``, and a
         *     session that began the previous day (a night shift) has no ``check_in`` on
         *     the day it closes.
         */
        AttendanceSessionResponse: {
            /** Check In */
            check_in?: string | null;
            /** Check Out */
            check_out?: string | null;
            /** Check In Event Id */
            check_in_event_id?: string | null;
            /** Check Out Event Id */
            check_out_event_id?: string | null;
        };
        /**
         * AttendanceState
         * @description A user's current attendance state.
         *
         *     Derived from their most recent attendance event - there is deliberately no
         *     ``current_status`` column. A denormalised status would be a second source of
         *     truth that can drift from the events, and the events are the audit record
         *     that matters.
         *
         *     ``CHECK_OUT`` returns a user to ``NOT_CHECKED_IN``, which is what allows
         *     repeated day-after-day cycles without any reset step.
         * @enum {string}
         */
        AttendanceState: "NOT_CHECKED_IN" | "CHECKED_IN";
        /**
         * AttendanceTodayResponse
         * @description The caller's (or a named user's) attendance for a single day.
         */
        AttendanceTodayResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            state: components["schemas"]["AttendanceState"];
            day: components["schemas"]["AttendanceDayResponse"];
        };
        /**
         * DayStatus
         * @description How one calendar day looks for one user.
         *
         *     ``NO_RECORD`` is named carefully. It states only that **no attendance event
         *     was recorded** for that day - it is *not* a claim that the person was absent
         *     from work. They may have been on leave, travelling, working elsewhere, or
         *     simply unable to reach the QR display; Karya has no way to tell, and leave
         *     and shift management do not exist yet. "ABSENT" would assert something the
         *     data does not support.
         *
         *     Distinct from :class:`AttendanceState`, which is the *live* state machine
         *     Phase 4 uses to accept or refuse a check-in. This enum describes a completed
         *     (or in-progress) day and therefore needs the third ``COMPLETED`` value.
         * @enum {string}
         */
        DayStatus: "NO_RECORD" | "CHECKED_IN" | "COMPLETED";
        /**
         * FailureReason
         * @description Why a presence attempt was rejected.
         *
         *     Some values are internal-only; see :data:`CLIENT_SAFE_REASON` for the
         *     mapping applied before a reason reaches an API response.
         * @enum {string}
         */
        FailureReason: "NO_ACTIVE_ATTENDANCE_LOCATION" | "GPS_INVALID" | "GPS_ACCURACY_TOO_LOW" | "OUTSIDE_GEOFENCE" | "QR_NOT_FOUND" | "QR_EXPIRED" | "QR_ALREADY_USED" | "QR_REVOKED" | "QR_NONCE_MISMATCH" | "QR_TENANT_MISMATCH" | "QR_LOCATION_MISMATCH";
        /**
         * GPSVerificationResult
         * @description Server-computed GPS outcome.
         */
        GPSVerificationResult: {
            /** Verified */
            verified: boolean;
            /** Distance Meters */
            distance_meters: number | null;
            /** Accuracy Meters */
            accuracy_meters: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Credentials for ``POST /api/v1/auth/login``.
         *
         *     The tenant is identified by slug: login is tenant-scoped, and the user
         *     lookup is constrained to the resolved tenant.
         */
        LoginRequest: {
            /** Tenant Slug */
            tenant_slug: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * PaginationResponse
         * @description Page metadata. ``total`` counts **days** in the range, not events.
         */
        PaginationResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PasswordChangeRequest
         * @description A self-service password change.
         *
         *     No user id: the account is always the authenticated caller, so there is no
         *     field through which an administrator could set someone else's password.
         */
        PasswordChangeRequest: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
        };
        /**
         * PasswordChangeResponse
         * @description Outcome of a password change.
         */
        PasswordChangeResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Sessions Revoked */
            sessions_revoked: number;
        };
        /**
         * PresenceStatus
         * @description Outcome of a presence-verification attempt.
         *
         *     Only two outcomes exist in Phase 3. ``MANUAL_REVIEW`` deliberately does not
         *     appear here: it belongs to ``AttendanceEvent.verification_status``, where
         *     Phase 4 can apply policy to a rejected-but-plausible attempt. Adding a third
         *     presence outcome now would be complexity with no consumer.
         * @enum {string}
         */
        PresenceStatus: "PRESENCE_VERIFIED" | "PRESENCE_REJECTED";
        /**
         * PresenceSummary
         * @description The presence evidence behind an attendance decision.
         */
        PresenceSummary: {
            /** Verified */
            verified: boolean;
            gps: components["schemas"]["GPSVerificationResult"];
            qr: components["schemas"]["QRVerificationResult"];
        };
        /**
         * PresenceVerificationRequest
         * @description Evidence submitted by a staff device.
         *
         *     Note what is absent: no identity, no tenant, no verdict, no distance. All of
         *     those are derived from the bearer token and the database.
         */
        PresenceVerificationRequest: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accuracy Meters */
            accuracy_meters: number;
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Nonce */
            nonce: string;
        };
        /**
         * PresenceVerificationResponse
         * @description The presence decision returned to the caller.
         */
        PresenceVerificationResponse: {
            /** Verified */
            verified: boolean;
            status: components["schemas"]["PresenceStatus"];
            gps: components["schemas"]["GPSVerificationResult"];
            qr: components["schemas"]["QRVerificationResult"];
            reason?: components["schemas"]["FailureReason"] | null;
        };
        /**
         * QRChallengeResponse
         * @description A freshly issued challenge, for the office display to render as a QR.
         *
         *     The display encodes ``challenge_id`` and ``nonce`` into the QR image; those
         *     two are all a phone needs to submit. Nothing else about the tenant, the
         *     location or its coordinates is included - the server stays authoritative and
         *     the QR stays compact.
         */
        QRChallengeResponse: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Nonce */
            nonce: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * QRVerificationResult
         * @description QR challenge outcome. Deliberately carries no nonce.
         */
        QRVerificationResult: {
            /** Verified */
            verified: boolean;
        };
        /**
         * RefreshTokenRequest
         * @description Body for ``POST /api/v1/auth/refresh`` and ``.../logout``.
         */
        RefreshTokenRequest: {
            /**
             * Refresh Token
             * Format: password
             */
            refresh_token: string;
        };
        /**
         * RoleUpdateRequest
         * @description A role change, on its own dedicated endpoint.
         */
        RoleUpdateRequest: {
            role: components["schemas"]["UserRole"];
        };
        /**
         * SelfUpdateRequest
         * @description Profile fields a user may change about themselves.
         *
         *     Narrower than the administrator's version: no email, because it is the login
         *     identity - changing it unilaterally is how somebody locks themselves out, and
         *     it belongs to the tenant's administration. No employee code either, since the
         *     tenant assigns it.
         */
        SelfUpdateRequest: {
            /** Name */
            name?: string | null;
        };
        /**
         * TeamAttendanceMember
         * @description One colleague on the tenant dashboard.
         *
         *     Identity is limited to what a manager needs to recognise the person. Email is
         *     deliberately omitted - it is contact data, not attendance data.
         */
        TeamAttendanceMember: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Employee Code */
            employee_code: string;
            status: components["schemas"]["DayStatus"];
            /** Check In */
            check_in?: string | null;
            /** Check Out */
            check_out?: string | null;
            /** Sessions */
            sessions?: components["schemas"]["AttendanceSessionResponse"][];
        };
        /**
         * TeamAttendanceResponse
         * @description Today's attendance across the caller's own tenant.
         */
        TeamAttendanceResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            summary: components["schemas"]["TeamAttendanceSummary"];
            /** Employees */
            employees: components["schemas"]["TeamAttendanceMember"][];
        };
        /**
         * TeamAttendanceSummary
         * @description Headcount by status. The three buckets always sum to ``total_staff``.
         */
        TeamAttendanceSummary: {
            /** Total Staff */
            total_staff: number;
            /** No Record */
            no_record: number;
            /** Checked In */
            checked_in: number;
            /** Completed */
            completed: number;
        };
        /**
         * TenantResponse
         * @description The caller's own tenant.
         */
        TenantResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TenantUpdateRequest
         * @description The only tenant field a tenant administrator may change.
         *
         *     ``slug`` is excluded even though it is human-readable metadata: it is the
         *     tenant identifier every user types at login, so changing it would silently
         *     lock out an entire company. ``status`` is excluded because tenant suspension
         *     is an operator action, not a self-service one. ``id`` and the timestamps are
         *     not writable anywhere.
         */
        TenantUpdateRequest: {
            /** Name */
            name?: string | null;
        };
        /**
         * TokenResponse
         * @description Credentials returned by login and refresh.
         *
         *     ``refresh_token`` is the only time the raw value is ever exposed; the server
         *     keeps just its hash.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * UserAuditEntryResponse
         * @description One lifecycle audit row.
         *
         *     ``metadata`` carries only identifiers and before/after values written by
         *     :mod:`app.services.users.service` - never a password, hash, token or nonce.
         */
        UserAuditEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * UserAuditResponse
         * @description A page of one user's lifecycle audit history.
         */
        UserAuditResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Items */
            items: components["schemas"]["UserAuditEntryResponse"][];
            pagination: components["schemas"]["UserListPagination"];
        };
        /**
         * UserCreateRequest
         * @description Fields a tenant administrator may supply when creating a user.
         *
         *     ``tenant_id`` is absent by design - the tenant comes from the authenticated
         *     administrator, so a user can only ever be created inside the caller's own
         *     tenant.
         */
        UserCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Name */
            name: string;
            /** Employee Code */
            employee_code: string;
            /** @default STAFF */
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserDetailResponse
         * @description A user as returned by the management endpoints.
         *
         *     Extends :class:`UserResponse` with lifecycle timestamps, which an
         *     administrator needs to see. Still an explicit allowlist - it inherits the
         *     named fields rather than serialising the ORM object, so a column added later
         *     cannot leak.
         */
        UserDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Employee Code */
            employee_code: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserListPagination
         * @description Page metadata for a user listing.
         */
        UserListPagination: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * UserListResponse
         * @description One page of the caller's own tenant's users.
         */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserDetailResponse"][];
            pagination: components["schemas"]["UserListPagination"];
        };
        /**
         * UserResponse
         * @description The authenticated user, as returned by ``GET /api/v1/auth/me``.
         *
         *     Deliberately excludes ``password_hash`` and every other authentication
         *     artefact. ``created_at``/``updated_at`` are omitted too - nothing needs them
         *     yet, and the narrower the response, the less there is to leak.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Employee Code */
            employee_code: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /**
         * UserRole
         * @description Roles a user may hold. Enforcement (RBAC) is a later phase.
         * @enum {string}
         */
        UserRole: "SUPER_ADMIN" | "TENANT_ADMIN" | "MANAGER" | "STAFF";
        /**
         * UserStatus
         * @description Lifecycle status of a user account.
         * @enum {string}
         */
        UserStatus: "ACTIVE" | "INACTIVE";
        /**
         * UserUpdateRequest
         * @description Profile fields a tenant administrator may change.
         *
         *     Deliberately excludes ``role`` and ``status``: those are lifecycle and
         *     privilege changes with their own endpoints, their own authorization and their
         *     own audit actions. Folding them into a generic update would make a privilege
         *     change indistinguishable from a typo correction in the audit trail.
         *
         *     PATCH semantics: every field is optional and only what is sent is written.
         */
        UserUpdateRequest: {
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Employee Code */
            employee_code?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Not ready - a required dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_qr_challenge_api_v1_presence_qr_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRChallengeResponse"];
                };
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active attendance location is configured */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_presence_api_v1_presence_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresenceVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceVerificationResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_in_api_v1_attendance_check_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceActionResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_out_api_v1_attendance_check_out_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceActionResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_my_attendance_api_v1_attendance_me_get: {
        parameters: {
            query?: {
                /** @description UTC date to report on, defaults to today */
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceTodayResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_history_api_v1_attendance_me_history_get: {
        parameters: {
            query?: {
                /** @description Inclusive start date (UTC) */
                from_date?: string | null;
                /** @description Inclusive end date (UTC), defaults to today */
                to_date?: string | null;
                /** @description 1-based page number */
                page?: number;
                /** @description Days per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceHistoryResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid date range or pagination */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_team_attendance_api_v1_attendance_team_today_get: {
        parameters: {
            query?: {
                /** @description UTC date to report on, defaults to today */
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAttendanceResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_attendance_api_v1_attendance_users__user_id__get: {
        parameters: {
            query?: {
                /** @description UTC date to report on, defaults to today */
                day?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceTodayResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_history_api_v1_attendance_users__user_id__history_get: {
        parameters: {
            query?: {
                /** @description Inclusive start date (UTC) */
                from_date?: string | null;
                /** @description Inclusive end date (UTC), defaults to today */
                to_date?: string | null;
                /** @description 1-based page number */
                page?: number;
                /** @description Days per page (max 100) */
                page_size?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceHistoryResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid date range or pagination */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_own_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_own_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_own_password_api_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordChangeResponse"];
                };
            };
            /** @description New password rejected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated, or current password incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                /** @description Match name, email or code */
                search?: string | null;
                /** @description Filter by role */
                role?: components["schemas"]["UserRole"] | null;
                /** @description Filter by status */
                status?: components["schemas"]["UserStatus"] | null;
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email or employee code already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email or employee code already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_user_role_api_v1_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions, or changing your own role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Would leave the tenant without an administrator */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivate_user_api_v1_users__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions, or deactivating yourself */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Would leave the tenant without an administrator */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate_user_api_v1_users__user_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_user_audit_api_v1_users__user_id__audit_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuditResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_own_tenant_api_v1_tenant_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_own_tenant_api_v1_tenant_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
