"""Declarative base, metadata naming convention and shared column mixins.

Every table in Karya uses:

* a UUID primary key (never an auto-increment integer), and
* timezone-aware ``TIMESTAMPTZ`` audit columns.

Both concerns live here so no model has to restate them.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic constraint/index names. Without this, Alembic emits unnamed
#: constraints that cannot be dropped by name in a downgrade.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all Karya ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds a UUIDv4 primary key named ``id``.

    The value is generated by the application (``uuid.uuid4``) so an object has
    its identity before it is flushed. ``gen_random_uuid()`` is also set as a
    server default so rows inserted by raw SQL or by a future data-migration
    still receive a valid UUID. Both produce UUIDv4, so the two paths are
    consistent; the application-side value always wins for ORM inserts.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        # Mixin columns are appended by default; keep `id` the first column.
        sort_order=-100,
    )


class CreatedAtMixin:
    """Adds an immutable, server-generated ``created_at`` timestamp."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        sort_order=100,
    )


class TimestampMixin(CreatedAtMixin):
    """Adds ``created_at`` plus a self-maintaining ``updated_at`` timestamp."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        sort_order=101,
    )
