"""Karya FastAPI application: composition root.

This module wires things together and contains no business logic. It is the one
place that decides middleware order, mounts routers, registers exception handlers
and owns the process lifecycle.

The application is built by :func:`create_app`, which takes its configuration as
an argument. ``app = create_app()`` at the bottom is what ``uvicorn app.main:app``
loads; the parameter exists so the wiring itself is testable - CORS behaviour,
security headers and whether the docs are served are *configuration-dependent*
behaviour, and a test that cannot vary the configuration cannot check any of them.

**Middleware order** (outermost first) is not arbitrary:

1. :class:`~app.middleware.security_headers.SecurityHeadersMiddleware` -
   outermost, so *every* response carries the hardening headers, including the
   responses generated by the middleware below it.
2. :class:`~app.middleware.request_context.RequestContextMiddleware` - correlation
   id, access log, and the last-resort 500. Outside CORS so a rejected preflight is
   still logged and still traceable.
3. ``CORSMiddleware`` - inside the two above so the responses it generates get
   both, and outside the size limits so a 413 still carries CORS headers and a
   browser reports the real status rather than an opaque CORS failure.
4. :class:`~app.middleware.request_limits.RequestLimitsMiddleware` - innermost,
   but still ahead of routing, so an oversized body is refused before it is
   buffered or parsed.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api import probes
from app.api.errors import register_exception_handlers
from app.api.v1.router import API_V1_PREFIX, api_router
from app.core.config import APP_VERSION, Settings, settings
from app.core.logging import configure_logging
from app.db.session import dispose_engine
from app.middleware.request_context import REQUEST_ID_HEADER, RequestContextMiddleware
from app.middleware.request_limits import RequestLimitsMiddleware
from app.middleware.security_headers import SecurityHeadersMiddleware

logger = logging.getLogger(__name__)

DESCRIPTION = """
Multi-tenant staff attendance with **server-verified presence**.

Every request is scoped to the authenticated user's own tenant. Identity, role,
tenant, GPS validity, geofence distance, QR validity and the attendance timestamp
are all determined by the server; no client-supplied value influences any of them.

**Authentication.** `POST /api/v1/auth/login` returns a short-lived JWT access
token and a long-lived, revocable refresh token. Send the access token as
`Authorization: Bearer <token>`. Refresh tokens must be rotated - the presented
token is revoked as part of a successful rotation, so replaying one fails.

**Errors.** Every error response is `{"detail": ...}`. Validation failures return
422 with a list of `{type, loc, msg}` under `detail`; the submitted value is never
echoed back. Rate-limited requests return 429 with a `Retry-After` header. Every
response, success or failure, carries an `X-Request-ID` header - quote it when
reporting a problem.

**Presence and attendance refusals are not HTTP errors.** A well-formed request
refused on its merits - outside the geofence, QR already used, already checked in -
returns **200** with `verified: false` or `success: false` and a machine-readable
`reason`. 4xx is reserved for requests that could not be processed at all.

**Nothing is ever deleted.** There is no `DELETE` method anywhere in this API.
Users move between `ACTIVE` and `INACTIVE`; attendance events are immutable.
"""

TAGS_METADATA = [
    {
        "name": "health",
        "description": (
            "Liveness and readiness probes. Unauthenticated, and deliberately "
            "uninformative: `/health` never touches the database, `/ready` does."
        ),
    },
    {
        "name": "auth",
        "description": (
            "Login, refresh-token rotation, logout and the caller's own profile. "
            "Every credential failure returns the same 401, so neither a tenant "
            "nor a user can be enumerated."
        ),
    },
    {
        "name": "presence",
        "description": (
            "GPS and dynamic-QR presence verification. Issuing a QR challenge is "
            "restricted to MANAGER and TENANT_ADMIN; verifying presence is open to "
            "any active user. A QR challenge is single-use and short-lived."
        ),
    },
    {
        "name": "attendance",
        "description": (
            "Check-in, check-out and read-only attendance views. Presence is "
            "re-verified server-side as part of every check-in and check-out. "
            "Reading another user's attendance requires MANAGER or TENANT_ADMIN."
        ),
    },
    {
        "name": "users",
        "description": (
            "Self-service account endpoints, open to any active user, and user "
            "administration, restricted to TENANT_ADMIN. MANAGER has no "
            "user-management powers."
        ),
    },
    {"name": "tenant", "description": "The caller's own tenant profile."},
]


def build_lifespan(config: Settings):  # noqa: ANN201 - returns an async CM factory
    """Create the lifespan handler for an application built from ``config``."""

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        """Process lifecycle.

        Startup deliberately does **not** touch the database. A dependency being
        briefly unavailable should not prevent the process from starting and
        reporting itself unready - that is what ``/ready`` is for, and a container
        that refuses to start cannot report anything at all.

        Shutdown disposes the connection pool. Uvicorn stops accepting connections
        and waits for in-flight requests before running this, so closing the pool
        here cannot interrupt a request that is still being served. Nothing else
        needs stopping: Karya runs no background tasks, timers or workers, which is
        why graceful shutdown is four lines rather than a subsystem.
        """
        configure_logging(config)
        logger.info(
            "application_startup",
            extra={
                "event": "application_startup",
                "version": APP_VERSION,
                "environment": config.environment.value,
                # The password-free rendering. The raw URL is never logged.
                "database": config.safe_database_uri,
                "auth_configured": config.is_auth_configured,
                "rate_limit_enabled": config.rate_limit_enabled,
                "cors_origin_count": len(config.cors_origins),
                "docs_enabled": config.docs_enabled,
            },
        )
        try:
            yield
        finally:
            logger.info(
                "application_shutdown", extra={"event": "application_shutdown"}
            )
            dispose_engine()

    return lifespan


def create_app(config: Settings | None = None) -> FastAPI:
    """Build a fully wired Karya application."""
    config = config or settings

    app = FastAPI(
        title=config.app_name,
        version=APP_VERSION,
        summary="Multi-tenant staff attendance and presence verification platform.",
        description=DESCRIPTION,
        openapi_tags=TAGS_METADATA,
        lifespan=build_lifespan(config),
        # Turning the docs off removes the schema endpoint too, which is the point:
        # they are one decision, not two.
        docs_url="/docs" if config.docs_enabled else None,
        redoc_url="/redoc" if config.docs_enabled else None,
        openapi_url="/openapi.json" if config.docs_enabled else None,
    )

    register_exception_handlers(app)

    # --- Middleware (added innermost first; see the module docstring) --------
    app.add_middleware(RequestLimitsMiddleware, config=config)

    # CORS is opt-in per origin, read from CORS_ALLOWED_ORIGINS. There is no
    # wildcard fallback: with credentialed requests a wildcard is both invalid per
    # the CORS spec and unsafe, and `Settings` rejects one outright. An empty list
    # means no browser origin is permitted, which is the safe default for a
    # backend-only deployment - and in that case the middleware is not installed at
    # all, so no `Access-Control-Allow-*` header is ever emitted.
    if config.cors_origins:
        app.add_middleware(
            CORSMiddleware,
            allow_origins=config.cors_origins,
            allow_credentials=True,
            allow_methods=["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS"],
            allow_headers=["Authorization", "Content-Type", REQUEST_ID_HEADER],
            # Without this a browser cannot read the correlation id, which makes it
            # useless to the frontend that would otherwise report it.
            expose_headers=[REQUEST_ID_HEADER, "Retry-After"],
        )

    app.add_middleware(RequestContextMiddleware)
    app.add_middleware(SecurityHeadersMiddleware, config=config)

    app.include_router(probes.router)
    app.include_router(api_router, prefix=API_V1_PREFIX)
    return app


#: The ASGI application `uvicorn app.main:app` loads.
app = create_app()
